sudo: false
language: node_js
node_js:
- '12'
env:
  matrix:
    secure: kliRssdiTGmJxqWrCR9XeFRkkTysuvR9CLrSmEg+FHFOC9CMkhL4Rg1SEveeTxJ2sbYDRIyQM/f0wa84RcVPYKk6OgbHGW9K0wSgmHdmChPiFOQoI+0rSA+n0GPuO/iGJZ3okhBxk/sYLgI+74881BkV4s4tGBk6XkmtKIS/1jP4lG8cI0ainzGUVGYTkLsjdwzn1DOgJJ6GJyb9a5h7oE041ML9660HxkC32S/K4cHtPRKzKlo6kScR2conaQ4R7GIoq0qCRu4jV9B6O5KJ0kcOT8/9W4t3ewImn9icZmAe54o/UrbxISbrdkzzivARjYFQ0qCf3gdPqXXjXGgtwNGZdC4GFkEOMCe6TS51QbqryjoeT5/Z7h0Kyqe6/2G6xOHEnKzG9evD/yKDLoDBAx212GUf9cvi6rFLS6VI6HmPlVNHcaZ9C3qMHrgCCmzFP4OuFhnccknnHfMjt8rwSUR9Q1Vau4cUpuB2tCSVu06S/+TMLW25sHXXNKrdxjJ4baRgYqgZxB3EHOnuY9kyTmkbersrjB9L+O53wOsN/qazidoatmMyt0oXe6aJzXOamsG618wZcGD37m/QtRIcQW0j8895BekqWAn2f4vUudFqv7CKU/pvH0tE5pjUBhpRniTTQu0QeOUiMglCqiNyp4vZ29zPIQUIvf6SzHt1cJo=
